cache: false
language: node_js
node_js:
  - "6.9.0"
install:
  - npm install
script:
  - npm run test-ci
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_success: never
    on_failure: change
